#!/bin/bash

query="$1"
response=$(curl -s https://integrate.api.nvidia.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer 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" \
  -d '{
    "model": "meta/llama3-70b-instruct",
    "messages": [
      {"role": "system", "content": "You are a helpful assistant."},
      {"role": "user", "content": "'"$query"'"}
    ],
    "temperature": 0.5,
    "top_p": 0.7,
    "max_tokens": 1024,
    "stream": true
  }')
# echo "$response" | grep -oP '"content":"\K[^"]+' | sed 's/\\n/\n/g'
echo -e "$response" | grep -oP '"content":"\K[^"]+' | tr -d '\n'
echo
